Repository kubenow/image, pull requests merged in 2018-04, with the labels that each got.

#39 Refactory AWS Tenancy Details
  .travis.yml
  bin/os_pp.sh
  bin/os_tf.sh
  requirements.sh
Labels: minor

#42 Fixing Bugs in Cron Script
  bin/clean_az_dupl.sh
  bin/clean_os_dupl.sh
  bin/cron_script.sh
  build-azure.json
Labels: enhancement

#45 Fixing kubedns version
  requirements.sh
Labels: stable/0.3

#44 Fixing Azure Bug Cron Script
  bin/cron_script.sh
Labels: enhancement

#47 Update CI notifications
  .travis.yml
Labels: stable/0.5
